name: Release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-win.txt

    - name: Run build script
      run: .\build-win.bat ${{ matrix.os }}_${{ matrix.arch }}_${{ github.ref_name }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Thermometer-MI_${{ matrix.os }}_${{ matrix.arch }}_${{ github.ref_name }}.exe
        path: .\dist\Thermometer-MI_${{ matrix.os }}_${{ matrix.arch }}_${{ github.ref_name }}.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4

    - name: List Artifacts
      run: ls

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          *.exe
